---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-ct-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: pr-number
      type: string
      description: pull request number
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: main
    - name: pr-url
      type: string
      description: url of the pull request
    - name: head-sha
      type: string
      description: git commit SHA
    - name: git-repo-full-name
      type: string
      description: The full name of the repository
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: kubeconfig-creator
      params:
        - name: url
          value: "https://api.cluster-h2ndv.sandbox2830.opentlc.com:6443"
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: kubeconfig-creator
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: run-ct-test
      taskRef:
        name: helm-ci-task
        kind: Task
      params:
        - name: charts
          value: deploy
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - kubeconfig-creator
  # github-add-comment
  finally:
    - name: add-comment-to-pr
      taskRef:
        name: github-add-comment
      params:
        - name: REQUEST_URL
          value: $(params.pr-url)
        - name: COMMENT_OR_FILE
          value: "Pipeline run status for PR#$(params.pr-number) is $(tasks.status)"
    - name: github-set-status
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.git-repo-full-name)
        - name: SHA
          value: $(params.head-sha)
        - name: DESCRIPTION
          value: An update to GitHub about our pipeline status
        - name: STATE
          value: "$(tasks.status)"
        - name: TARGET_URL
          value: 'https://console-openshift-console.apps.cluster-h2ndv.sandbox2830.opentlc.com/k8s/ns/helm-tekton-pipeline/tekton.dev~v1beta1~PipelineRun/$(context.pipelineRun.name)'
