---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: helm-ct-pr
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: main
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: pr-number
      description: the pull request number
    - name: pr-url
      description: the pull request url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: helm-ct-pipeline-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: helm-ct-pipeline
        params:
          - name: pr-number
            value: $(tt.params.pr-number)
          - name: pr-url
            value: $(tt.params.pr-url)
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
