apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ct-helm-task-sa-edit
  namespace: helm-tekton-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: ct-helm-task
  namespace: helm-tekton-pipeline
