apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-ci-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Developer Tools
    tekton.dev/tags: helm,lint,test
    tekton.dev/displayName: "Helm CI Lint&Test"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to replace fields in YAML files. For example for altering helm charts on GitOps repos.
  workspaces:
    - name: source
      description: A workspace that contains the file which needs to be altered.
  params:
    - name: image
      type: string
      description: The chart testing image to use.
      default: quay.io/helmpack/chart-testing:v3.7.1
    - name: chart-dirs
      type: string
      description: directory of the charts
      default: "charts/"
    - name: charts
      type: string
      description: name of the chart to test
      default: ""
    - name: namespace
      type: string
      description: namespace to run ci tests
      default: "helm-demo"
    - name: ct-config-file
      type: string
      description: config file for running ct commands
      default: "ct.yaml"
    - name: skip-cleanup
      type: string
      description: Skip cleanup of resources
      default: "false"
  steps:
    - name: ci-script
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        ct install --chart-dirs $(params.chart-dirs) --charts $(params.charts) --namespace $(params.namespace) --config $(params.ct-config-file) --skip-clean-up $(params.skip-cleanup)
      
