apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-ct-pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: pr-number
    type: string
    description: pull request number
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: master
  - name: pr-url
    type: string
    description: url of the pull request
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: kubeconfig-creator
    params:
      - name: url
        value: 'https://api.cluster-h2ndv.sandbox2830.opentlc.com:6443'
    runAfter:
      - fetch-repository
    taskRef:
      kind: Task
      name: kubeconfig-creator
    workspaces:
      - name: output
        workspace: shared-workspace
  - name: run-ct-test
    taskRef:
      name: helm-ci-task
      kind: Task
    params:
    - name: charts
      value: deploy
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - kubeconfig-creator
  # github-add-comment
  finally:
    - name: add-comment-to-pr
      taskRef:
        - name: github-add-comment
          kind: Task
      params:
      - name: REQUEST_URL
        value: $(params.pr-url)
      - name: COMMENT_OR_FILE
        value: temporary dummy comment for pull request $(params.pr-number)
