---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-github-release
spec:
  workspaces:
    - name: source
  params:
    - name: TAG
      description: A git tag that will be created with this release (e.g. v1.0.0)
      type: string
    - name: REVISION
      type: string
      description: Git revision to create a release from (branch, tag, sha, ref…).
      default: main
    - name: RELEASE_FILE_NAME
      type: string
      description: Name of the file that has to be uploaded as release notes.
      default: release.md
    - name: GITHUB_TOKEN_SECRET
      type: string
      description: Name of the secret holding the github-token.
      default: github
    - name: GITHUB_TOKEN_SECRET_KEY
      type: string
      description: Name of the secret key holding the github-token.
      default: token
  steps:
    - name: create-release
      workingdir: $(workspaces.source.path)
      image: quay.io/diagrawa/github-hub:latest
      script: |
        #!/usr/bin/env bash
        set -ex

        echo $(params.RELEASE_FILE_NAME)
        # Create a release
        echo "Creating release $(params.TAG)"

        hub release create \
          --commitish $(params.REVISION) \
          --file $(workspaces.source.path)/$(params.RELEASE_FILE_NAME) \
          $(params.TAG)
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.GITHUB_TOKEN_SECRET)
              key: $(params.GITHUB_TOKEN_SECRET_KEY)
